---
# https://pre-commit.com/
# Install pre-commit itself (once):
#   $ brew install pre-commit
# Add to your git hooks (once per repo):
#   $ pre-commit install
# Manually run all hooks (any time):
#   $ pre-commit run -a

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-json # Attempts to load all json files to verify syntax.
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace # Trims trailing whitespace.
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.10.2
    hooks:
      - id: forbid-binary
        exclude: ^public-websites/marketing-host/ansible/files/mod_cloudflare-trusty-amd64.latest.deb$
      - id: git-check
      - id: shellcheck
        files: \.tpl$
        exclude: inventory.tpl$
        types: [file]
        args: ['-e', 'SC2154', '-e', 'SC2086', '-e', 'SC1091', '-e', 'SC2034']
      - id: shfmt
        files: \.tpl$
        types: [file]
        args: ['-l', '-i', '2', '-ci', '-w']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.21.0
    hooks:
      - id: terraform_fmt
        files: \.tf$
      - id: terraform_validate
      - id: terraform_docs
